image: ligo/builder:el7

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - yum-cache
    - pip-cache
    - .eggs

before_script:
  # Configure yum cache
  - sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf
  - sed -i 's|cachedir=.*|cachedir='$(pwd)'/yum-cache|' /etc/yum.conf
  - mkdir -p yum-cache
  # Configure pip cache
  - echo [global] >> /etc/pip.conf
  - echo cache-dir = $(pwd)/pip-cache >> /etc/pip.conf
  - mkdir -p pip-cache

build:
  stage: build
  script:
    - yum install -y python36u-pip
    - pip3.6 install wheel
    - python3.6 setup.py sdist -d . bdist_wheel -d .
  artifacts:
    paths:
      - '*.tar.*'
      - '*.whl'

test:
  variables:
    GIT_STRATEGY: none
  tags:
    - highmem
  stage: test
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    - yum install -y python36u-pip python36u-devel
    - tar --strip-components 1 -xf *.tar.*
    - LANG=en_US.UTF-8 pip3.6 install pytest-cov pytest-runner pytest-flake8 .
    - python3.6 setup.py test --addopts='-vv --cov --cov-report=html --cov-report=term --flake8'
  artifacts:
    paths:
      - htmlcov/

doc:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - yum install -y python36u-setuptools
    - tar --strip-components 1 -xf *.tar.*
    - python3.6 setup.py build_sphinx -W
  artifacts:
    paths:
      - build/sphinx/html

pages:
  stage: deploy
  script:
    - mv build/sphinx/html public/
    - mv htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
