image: ligo/builder:el7

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - yum-cache
    - pip-cache
    - .eggs

before_script:
  # Configure yum cache
  - sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf
  - sed -i 's|cachedir=.*|cachedir='$(pwd)'/yum-cache|' /etc/yum.conf
  - mkdir -p yum-cache
  # Configure pip cache
  - echo [global] >> /etc/pip.conf
  - echo cache-dir = $(pwd)/pip-cache >> /etc/pip.conf
  - mkdir -p pip-cache

build:
  stage: build
  script:
    - yum install -y python-pip
    - pip install --upgrade setuptools wheel
    - python setup.py sdist -d . bdist_wheel -d .
  artifacts:
    paths:
      - '*.tar.*'
      - '*.whl'

test:
  variables:
    GIT_STRATEGY: none
  tags:
    - highmem
  stage: test
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    # Install dependencies
    - yum install -y python-pip lalinference-python
    - pip install --upgrade setuptools
    - pip install pytest-cov pytest-codestyle
    # Run tests
    - tar --strip-components 1 -xf *.tar.*
    - python setup.py test --addopts='-vv --cov --cov-report=html --cov-report=term --codestyle'
  artifacts:
    paths:
      - htmlcov/

test:python36:
  variables:
    GIT_STRATEGY: none
  script:
    # Install dependencies
    - yum install -y python36u-pip
    - pip3.6 install pytest-runner
    # Run tests
    - tar --strip-components 1 -xf *.tar.*
    - pip3.6 install .
    - python3.6 setup.py test --addopts='-vv'

doc:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - yum install -y python36u-setuptools
    - tar --strip-components 1 -xf *.tar.*
    - python3.6 setup.py build_sphinx -W
  artifacts:
    paths:
      - build/sphinx/html

pages:
  stage: deploy
  script:
    - mv build/sphinx/html public/
    - mv htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
