image: ligo/builder:el7

cache:
  paths:
    - ~/.cache/pip

before_script:
  - yum install -y python-pip pyxmpp
  - pip install --upgrade pip setuptools

test:
  script:
    - pip install .
    - python setup.py test --addopts=-vv
