image: ligo/builder:el7

variables:
  CELERY_BROKER_URL: redis://redis
  GIT_STRATEGY: clone

stages:
  - test
  - deploy

cache:
  paths:
    - yum-cache
    - pip-cache

before_script:
  # Configure yum cache
  - sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf
  - sed -i 's|cachedir=.*|cachedir='$(pwd)'/yum-cache|' /etc/yum.conf
  - mkdir -p yum-cache
  # Configure pip cache
  - echo [global] >> /etc/pip.conf
  - echo cache-dir = $(pwd)/pip-cache >> /etc/pip.conf
  - mkdir -p pip-cache

test:
  services:
    - redis:3.2.11
  tags:
    - highmem
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    # Install dependencies
    - yum install -y python-pip lalinference-python
    - pip install --upgrade pytest-cov pytest-runner mock
    - pip install .
    # Run tests
    - python setup.py test --addopts='-vv --cov --cov-report=html --cov-report=term'
  artifacts:
    paths:
      - htmlcov/

doc:
  script:
    - yum install -y python-pip
    - pip install sphinx
    - pip install .
    - python setup.py build_sphinx
  artifacts:
    paths:
      - build/sphinx/html

pages:
  stage: deploy
  script:
    - mv build/sphinx/html/* htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
