image: ligo/builder:el7

variables:
  PIP_CACHE: "pip-cache"

cache:
  paths:
    - /var/cache/yum
    - $PIP_CACHE

stages:
  - test
  - deploy
  - mirror

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    - echo keepcache = 1 >> /etc/yum.conf
    - yum install -y python-pip pyxmpp lalinference-python yum-plugin-priorities
    - rpm -Uvh http://software.ligo.org/lscsoft/scientific/7/x86_64/production/lscsoft-epel-config-1.4-1.el7.noarch.rpm
    - rpm -Uvh https://repo.grid.iu.edu/osg/3.3/osg-3.3-el7-release-latest.rpm
    - rpm -Uvh http://software.ligo.org/lscsoft/scientific/7/x86_64/production/lscsoft-production-config-1.3-1.el7.noarch.rpm
    - yum install -y osg-oasis ldg-client
    - echo /cvmfs /etc/auto.cvmfs >> /etc/auto.master
    - systemctl restart autofs
    - sed -i 's/#[[:space:]]*user_allow_other/user_allow_other/' /etc/fuse.conf
    - cat /etc/fuse.conf
    - ls -lh /cvmfs/oasis.opensciencegrid.org/ligo/sw
    - mkdir -p "$PIP_CACHE"
    - pip install --cache-dir="$PIP_CACHE" --upgrade pip setuptools pytest-cov pytest-runner mock
    - pip install --cache-dir="$PIP_CACHE" .
    - python setup.py test --addopts='--cov --cov-report=html --cov-report=term'
  artifacts:
    paths:
      - htmlcov/

mirror:
  script:
    - mkdir -p ~/.ssh
    - echo -e $GITHUB_DEPLOY_ID_RSA > ~/.ssh/id_rsa
    - echo -e $GITHUB_DEPLOY_ID_RSA_PUB > ~/.ssh/id_rsa.pub
    - git remote set-url github git@github.com:lpsinger/gwcelery.git || git remote add github git@github.com:lpsinger/gwcelery.git
    - git push github master

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
