image: ligo/builder:el7

variables:
  CELERY_BROKER_URL: redis://redis
  GIT_STRATEGY: clone

stages:
  - test
  - deploy
  - mirror

test:
  cache:
    paths:
      - yum-cache
      - pip-cache
  services:
    - redis:3.2.11
  tags:
    - highmem
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  before_script:
    # Install yum dependencies
    - sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf
    - sed -i 's|cachedir=.*|cachedir='$(pwd)'/yum-cache|' /etc/yum.conf
    - mkdir -p yum-cache
    - yum install -y python-pip lalinference-python
    # Install pip dependencies
    - mkdir -p pip-cache
    - pip install --cache-dir=pip-cache --upgrade pytest-cov pytest-runner mock
    - pip install --cache-dir=pip-cache .
  script:
    - python setup.py test --addopts='-vv --cov --cov-report=html --cov-report=term'
  artifacts:
    paths:
      - htmlcov/

mirror:
  before_script:
    - mkdir -p ~/.ssh
    - echo 'github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
    - echo -e "$GITHUB_DEPLOY_ID_RSA" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git push --mirror git@github.com:lpsinger/gwcelery.git

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
