image: ligo/builder:el7

variables:
  PIP_CACHE: "pip-cache"

cache:
  paths:
    - /var/cache/yum
    - $PIP_CACHE

stages:
  - test
  - deploy
  - mirror

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    - echo keepcache = 1 >> /etc/yum.conf
    - yum install -y python-pip pyxmpp lalinference-python yum-plugin-priorities
    - yum install -y osg-oasis ldg-client
    - echo /cvmfs /etc/auto.cvmfs >> /etc/auto.master
    - sed -i 's/#[[:space:]]*user_allow_other/user_allow_other/' /etc/fuse.conf
    - systemctl restart autofs
    - ls -lh /cvmfs/oasis.opensciencegrid.org/ligo/sw
    - mkdir -p "$PIP_CACHE"
    - pip install --cache-dir="$PIP_CACHE" --upgrade pip setuptools pytest-cov pytest-runner mock
    - pip install --cache-dir="$PIP_CACHE" .
    - python setup.py test --addopts='--cov --cov-report=html --cov-report=term'
  artifacts:
    paths:
      - htmlcov/

mirror:
  script:
    - mkdir -p ~/.ssh
    - echo 'github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
    - echo -e "$GITHUB_DEPLOY_ID_RSA" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - echo -e "$GITHUB_DEPLOY_ID_RSA_PUB" > ~/.ssh/id_rsa.pub && chmod 0600 ~/.ssh/id_rsa.pub
    - git remote set-url github git@github.com:lpsinger/gwcelery.git || git remote add github git@github.com:lpsinger/gwcelery.git
    - git push -f github master

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
