image: ligo/builder:el7

cache:
  paths:
    - /.cache/pip

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    - yum install -y python-pip pyxmpp
    - pip install --verbose --upgrade pip setuptools pytest-cov
    - pip install .
    - python setup.py test --addopts=''--cov --cov-report=html --cov-report=term'
  artifacts:
    paths:
      - htmlcov/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
