image: ligo/builder:el7

variables:
  PIP_CACHE: "pip-cache"

cache:
  paths:
    - /var/cache/yum
    - $PIP_CACHE

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    - mkdir -p "$PIP_CACHE"
    - yum install -y python-pip pyxmpp
    - pip install --cache-dir="$PIP_CACHE" --upgrade pip setuptools pytest-cov
    - pip install --cache-dir="$PIP_CACHE" .
    - python setup.py test --addopts='--cov --cov-report=html --cov-report=term'
  artifacts:
    paths:
      - htmlcov/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
