image: ligo/builder:el7

cache:
  paths:
    - ~/.cache/pip

before_script:
  - yum install -y python-pip pyxmpp
  - pip install --upgrade pip setuptools pytest-cov

test:
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  script:
    - pip install .
    - python setup.py test --addopts='-vv --cov'
