stages:
  - dist
  - dependencies
  - test
  - deploy

# Build Python packages
dist:
  image: python:3.7-slim
  stage: dist
  script:
    - python setup.py sdist bdist_wheel
    - mv dist/* .
  artifacts:
    paths:
      - '*.tar.gz'
      - '*.whl'

# Allow Celery to run as root, because everything runs as root under Docker.
variables:
  C_FORCE_ROOT: 'true'

# Build Docker container for dependencies
.dependencies: &dependencies
  stage: dist
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_NAME
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      cat <<EOF > Dockerfile
      FROM python:${CI_JOB_NAME#*python}
      COPY requirements.txt .
      RUN pip --no-cache-dir install -r requirements.txt
      RUN rm -f requirements.txt
      EOF
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - if [ "${CI_COMMIT_TAG:0:1}" = "v" ]; then docker tag $IMAGE_TAG ${IMAGE_TAG%:*}:latest; docker push ${IMAGE_TAG%:*}:latest; fi
dependencies/python3.6:
  <<: *dependencies
dependencies/python3.7:
  <<: *dependencies

# Build docker container for application itself
.docker: &docker
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - IMAGE_TAG=$CI_REGISTRY_IMAGE/${CI_JOB_NAME#*/}:$CI_COMMIT_REF_NAME
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - |
      cat <<EOF > Dockerfile
      FROM $CI_REGISTRY_IMAGE/dependencies/${CI_JOB_NAME#*/}:$CI_COMMIT_REF_NAME
      COPY *.whl .
      RUN pip install *.whl
      RUN rm -f *.whl
      USER nobody
      WORKDIR /tmp
      ENTRYPOINT ["gwcelery"]
      EOF
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - if [ "${CI_COMMIT_TAG:0:1}" = "v" ]; then docker tag $IMAGE_TAG ${IMAGE_TAG%:*}:latest; docker push ${IMAGE_TAG%:*}:latest; fi
  dependencies:
    - dist
docker/python3.6:
  <<: *docker
docker/python3.7:
  <<: *docker

# Run unit tests and coverage measurement
.test: &test
  stage: test
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  variables:
    GIT_STRATEGY: none
  before_script:
    - apt-get update -qq && apt-get install -y -qq redis-server
  script:
    - tar --strip-components 1 -xf *.tar.*
    - pip install pytest-cov
    - python setup.py test --addopts='-vv --cov --cov-report=html --cov-report=term'
  dependencies:
    - dist
  artifacts:
    paths:
      - htmlcov/
test/python3.6:
  image: $CI_REGISTRY_IMAGE/dependencies/python3.6:$CI_COMMIT_REF_NAME
  <<: *test
test/python3.7:
  image: $CI_REGISTRY_IMAGE/dependencies/python3.7:$CI_COMMIT_REF_NAME
  <<: *test

lint:
  image: $CI_REGISTRY_IMAGE/dependencies/python3.7:$CI_COMMIT_REF_NAME
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - tar --strip-components 1 -xf *.tar.*
    - pip install flake8 pep8-naming
    - flake8 --show-source .
  dependencies:
    - dist

# Generate documentation
doc:
  image: python:3.7-slim
  stage: test
  variables:
    GIT_STRATEGY: none
  before_script:
    - apt-get update -qq && apt-get install -y -qq graphviz
  script:
    - tar --strip-components 1 -xf *.tar.*
    - python setup.py build_sphinx
  dependencies:
    - dist

# Publish coverage
pages:
  stage: deploy
  script:
    - mv htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  dependencies:
    - test/python3.7

# Upload package to PyPI
pypi:
  stage: deploy
  image: python:3.7-slim
  variables:
    GIT_STRATEGY: none
  script:
    - pip install twine
    - twine upload *.tar.* *.whl
  dependencies:
    - dist
  only:
    - tags@emfollow/gwcelery
