stages:
  - dist
  - dependencies
  - test
  - deploy

.docker: &docker
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  after_script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# Build Python packages
dist:
  image: python:slim
  stage: dist
  script:
    - python setup.py sdist bdist_wheel
    - mv *.egg-info/requires.txt requirements.txt
    - mv dist/* .
  artifacts:
    paths:
      - '*.tar.gz'
      - '*.whl'
      - requirements.txt

# Build Docker container for dependencies
dependencies:
  stage: dependencies
  variables:
    GIT_STRATEGY: none
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_JOB_NAME:$CI_COMMIT_REF_NAME
  script:
    - |
      cat <<EOF > Dockerfile
      FROM python
      COPY requirements.txt .
      RUN pip --no-cache-dir install -r requirements.txt
      RUN rm -f requirements.txt
  dependencies:
    - dist
  <<: *docker


# Build docker container for application itself
docker:
  stage: test
  variables:
    GIT_STRATEGY: none
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
    - |
      cat <<EOF > Dockerfile
      FROM $CI_REGISTRY_IMAGE/dependencies:$CI_COMMIT_REF_NAME
      COPY *.whl .
      RUN pip install *.whl
      RUN rm -f *.whl
      USER nobody
      WORKDIR /tmp
      ENTRYPOINT ["gwcelery"]
      EOF
  dependencies:
    - dist
  <<: *docker

# Run unit tests and coverage measurement
test:
  image: $CI_REGISTRY_IMAGE/dependencies:$CI_COMMIT_REF_NAME
  stage: test
  coverage: '/^TOTAL\s+.*\s+(\d+\.?\d*)%/'
  variables:
    GIT_STRATEGY: none
  script:
    - tar --strip-components 1 -xf *.tar.*
    - pip install pytest-cov
    - python setup.py test --addopts='-vv --cov --cov-report=html --cov-report=term'
  dependencies:
    - dist
  artifacts:
    paths:
      - htmlcov/

lint:
  image: $CI_REGISTRY_IMAGE/dependencies:$CI_COMMIT_REF_NAME
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - tar --strip-components 1 -xf *.tar.*
    - pip install flake8
    - flake8 --show-source .
  dependencies:
    - dist

# Generate documentation
doc:
  image: python:slim
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - tar --strip-components 1 -xf *.tar.*
    - python setup.py build_sphinx -W
  dependencies:
    - dist
  artifacts:
    paths:
      - build/sphinx/html

# Publish docs and coverage
pages:
  stage: deploy
  script:
    - mv build/sphinx/html public/
    - mv htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

# Upload package to PyPI
pypi:
  stage: deploy
  image: python:slim
  variables:
    GIT_STRATEGY: none
  script:
    - pip install twine
    - twine upload *.tar.* *.whl
  dependencies:
    - dist
  only:
    - tags@emfollow/gwcelery
